development:
  secret_token: <%= ENV['secret_token'] %>
  secret_key_base: <%= ENV['secret_key_base'] %>

test:
  secret_token: '123'
  secret_key_base: '12345'

production:
  secret_token: <%= ENV['secret_token'] %>
  secret_key_base: <%= ENV['secret_key_base'] %>
